### ISSUE TITLE
issue with require path

### ISSUE THREAD

**Issue by drourke** [Fabriquartz/ember-keyboard-service#2]
In the docs it says to use 
`import KeyboardMixin from 'ember-keyboard-service;`, 

I had to make it in order to make it work. 
`import KeyboardMixin from 'ember-keyboard-service/mixins/keyboard';` 

Not sure if its a typo in docs.

**Comment by martndemus** [comment]
Yes thats a typo in the docs. I have updated the docs in 0c06e67.

**Comment by drourke** [comment]
Awesome, thanks!
