### ISSUE TITLE
When using listener arguments, the event is duplicated in the arguments.

### ISSUE THREAD

**Issue by DanChadwick** [Fabriquartz/ember-keyboard-service#5]
If you specify an argument to the event listener, the first keystoke calls the listener with (event, ...args). The next time it calls it with (event, oldevent, ...args), and so forth.

In services/keyboard.js, function _handleKeyPress():
```javascript
      // Push the event object onto arguments
      // const args = options.arguments || [];
      // args.unshift(e);
      const args = [e].concat(options.arguments || []);
```

The original code inadvertently modifies options.arguments. There might be a more elegant way of doing this -- not sure.

**Comment by martndemus** [comment]
I'll look into this when I can.
